// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz_zNY9Wnu3F8bDsAUdi-ICazvkR2C-Tw',
    appId: '1:924408015570:web:257a69285298cd7a991b0b',
    messagingSenderId: '924408015570',
    projectId: 'chat-dd643',
    authDomain: 'chat-dd643.firebaseapp.com',
    storageBucket: 'chat-dd643.firebasestorage.app',
    measurementId: 'G-RR27YHCMGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9JA3PITd1tAxbxJWV6L43RVtyI1DvcAI',
    appId: '1:924408015570:android:1b9d1e70bf77747e991b0b',
    messagingSenderId: '924408015570',
    projectId: 'chat-dd643',
    storageBucket: 'chat-dd643.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_NENlkzCwyMPQD9uW0SAGvQ-gZnyMZV0',
    appId: '1:924408015570:ios:679a54187eb13b95991b0b',
    messagingSenderId: '924408015570',
    projectId: 'chat-dd643',
    storageBucket: 'chat-dd643.firebasestorage.app',
    iosBundleId: 'com.example.scholarchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_NENlkzCwyMPQD9uW0SAGvQ-gZnyMZV0',
    appId: '1:924408015570:ios:679a54187eb13b95991b0b',
    messagingSenderId: '924408015570',
    projectId: 'chat-dd643',
    storageBucket: 'chat-dd643.firebasestorage.app',
    iosBundleId: 'com.example.scholarchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz_zNY9Wnu3F8bDsAUdi-ICazvkR2C-Tw',
    appId: '1:924408015570:web:c2d74a7bed007829991b0b',
    messagingSenderId: '924408015570',
    projectId: 'chat-dd643',
    authDomain: 'chat-dd643.firebaseapp.com',
    storageBucket: 'chat-dd643.firebasestorage.app',
    measurementId: 'G-FMYGHZ7QQX',
  );

}